<?php 
/**
 * @category Dsdata
 * @package Dsdata_ProductPrint
 * @authors Daniel Sasse <info@dsdata.de, http://www.dsdata.de/>
 * @developer Daniel Sasse <info@dsdata.de, http://www.dsdata.de/>  
 * @version 0.1.1
 * @copyright dsdata.de, Daniel Sasse
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)  
 */
?>

<div class="printbuttons">

<?php // Adds a JavaScript PopUp Link that loads a seperate print view ?>
<script type="text/javascript">
<!--
function productprint(){
window.open("<?php echo $this->getBaseurl();?>printview/product/print/id/<?php echo $this->getProduct()->getId();?>","format","top=0,left=0,width=820,height=600,menubar=no,toolbar=no,scrollbars=yes,status=no,resizable=no,location=no,hotkeys=no")
}
//-->}
</script>

<a href="javascript:productprint()" class="printbutton" title="<?php echo $this->getProduct()->getName();?>" alt="<?php echo $this->getProduct()->getName();?>"><?php echo $this->__('Print PopUp') ?></a>

<?php // Adds a generate pdf link ?>
<?php 
/*
<a href="<?php echo $this->getBaseurl();?>printview/product/pdf/id/<?php echo $this->getProduct()->getId();?>" class="pdfbutton" title="<?php echo $this->getProduct()->getName();?>" alt="<?php echo $this->getProduct()->getName();?>"><?php echo $this->__('PDF') ?></a>
*/
?>
<?php //Link that opens Print dialog ?>
<a href="#" onClick="window.print();return false" class="printbutton" title="<?php echo $this->getProduct()->getName();?>" alt="<?php echo $this->getProduct()->getName();?>"><?php echo $this->__('Direct Print') ?></a> 

<?php
/**
* <a href="<?php echo $this->getBaseurl();?>printview/product/print/id/<?php echo $this->getProduct()->getId();?>" target="_blank" style="float:left; margin:7px 0 0 5px;"><button type="button" title="<?php echo $this->__('Print This Page') ?>" class="button"><span><?php echo $this->__('Print This Page') ?></span></button></a>
*/
?>

</div>

